slayfield/config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :show, :create, :destroy] do
    resources :teams, only: [:index, :show, :create] do
      resources :characters, only: [:index, :create] do
        resources :actions, only: [:create]
      end
    end
  end

  root to: 'games#index'
end

slayfield/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

slayfield/app/models/character.rb
# Character prototype
class Character < ApplicationRecord
  belongs_to :team
  validates_numericality_of :health, only_integer: true, greater_than_or_equal_to: 0
  serialize :hit_locations, JSON

  def take_damage(damage)
    damage = self.health if self.health < damage
    self.decrement('health', damage)
    save!
    damage
  end

  def valid_targets
    # opposing_teams = team.game.teams.select{|t| t.id != self.team.id}
    opposing_teams = team.game.teams.where.not(id: self.team.id)
    all_opposing_characters = opposing_teams.reduce([]){ |all, t| all += t.characters }
    all_opposing_characters.select(&:alive?)
  end

  def hit_location(dice_result)
    (hit_locations[dice_result.to_s]||:miss).to_sym
  end

  def alive?
    health > 0
  end
end

slayfield/app/models/game.rb
# This implements character class (with no character card)
class Game < ApplicationRecord
  has_many :teams, dependent: :destroy
  has_many :logs, dependent: :destroy
  validate :require_two_teams

  def winner
    alive_teams = teams.find_all{ |t| t.has_alive_characters }
    alive_teams.count == 1 ? alive_teams.first : nil
  end

  def characters
    teams.reduce([]){ |all, t| all += t.characters }
  end

  def character_by_name(name)
    characters.find{ |c| c.name == name }
  end

  def manage_turns
    unless teams.exists?(finished_turn: false) then
      ActiveRecord::Base.transaction do
        teams.each do |t|
          t.finished_turn = false
          t.save!
        end
        self.increment('turn')
        add_log_entry("Turn #{turn} has started")
        save!
      end
    end
  end

  def add_log_entry (action)
    self.logs.create(turn: turn, action: action, step: step)
  end

  private

  def step
    self.logs.where(turn: turn).count
  end

  def require_two_teams
    raise('Game must contain at least two teams') if teams.size < 2
  end
end

slayfield/app/models/log.rb
# This implements character class (with no character card)
class Log < ApplicationRecord
  belongs_to :game

end

slayfield/app/models/team.rb
# This implements character class (with no character card)
class Team < ApplicationRecord
  belongs_to :game
  has_many :characters, dependent: :destroy
  validate :require_characters

  def has_alive_characters
    characters.select{ |c| c.alive? }.count > 0
  end

  private

  def require_characters
    raise('Game must contain at least one characters') unless characters
  end
end

slayfield/app/controllers/actions_controller.rb
# Executing attacks for a @character in a resty way
class ActionsController < ApplicationController
  before_action :find_objects, only: [:create]

  def create
    service = ActionService.by_type(@type, @game, @character, @target)
    service.call
    redirect_to @game
  end

  private

  def find_objects
    @game = Game.find(params[:game_id])
    @character = Character.find(params[:character_id])
    @type = params[:type].to_sym
    @target = Character.find_by(id: params[:target_id])
  end
end

slayfield/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

slayfield/app/controllers/games_controller.rb
# Manages game sesssions
class GamesController < ApplicationController
  before_action :find_game, only: [:show, :destroy]

  def index
    @games = Game.all
  end

  def create
    service = CreateGame.new
    service.call
    redirect_to games_path
  end

  def show
    @teams = @game.teams
  end

  def destroy
    @game.destroy
    redirect_to games_path
  end

  private

  def find_game
    @game = Game.find(params[:id])
  end
end

slayfield/app/helpers/application_helper.rb
module ApplicationHelper
end

slayfield/app/views/characters/_character.html.erb
<div id="character_<%=character.id%>">
<p>Name: <b id="character_<%=character.id%>_name"><%= character.name %></b></p>
<p>Health: <b id="character_<%=character.id%>_health"><%= character.health %></b></p>
<p>Power: <b id="character_<%=character.id%>_power"><%= character.power %></b></p>
<p>Hit locations: <b id="character_<%=character.id%>_hit_locations"><%= character.hit_locations.inspect %></b></p>
<% if character.alive? %>
  <% unless @team.finished_turn %>
    <% character.valid_targets.each do |c| %>
      <%= form_for :action, :url => game_team_character_actions_path(@game, @team, character) do |f| %>
        <%= hidden_field_tag(:type, :damage) %>
        <%= hidden_field_tag(:target_id, c.id) %>
        <%= f.submit "Damage " + (character == c ? 'self' : c.name) %>
      <% end %>
      <%= form_for :action, :url => game_team_character_actions_path(@game, @team, character) do |f| %>
        <%= hidden_field_tag(:type, :regular_attack) %>
        <%= hidden_field_tag(:target_id, c.id) %>
        <%= f.submit "Attack " + (character == c ? 'self' : c.name) %>
      <% end %>
    <% end %>
    <%= form_for :action, :url => game_team_character_actions_path(@game, @team, character) do |f| %>
        <%= hidden_field_tag(:type, :skip) %>
        <%= f.submit "Skip turn" %>
      <% end %>
  <% end %>
<% else %>
  <b> DEAD </b>
<% end %>
</div>
<hr>

slayfield/app/views/games/_game.html.erb
<tr id="game_<%=game.id %>" >
  <td>
    <%= game.created_at.strftime('Game at %H:%M') %>
  </td>
  <td>
    <%= link_to 'Show', game_path(game) %>
    <%= link_to 'Clear', game_path(game), remote: true, method: :delete %>
  </td>
</tr>

slayfield/app/views/games/index.html.erb
<h1>Slayfield</h1>
<h2>List of games</h2>

<%= form_for :game do |f| %>
  <%= f.submit "New Game"%>
<% end %>

<table id="games">
  <tr>
    <th>Game</th>
    <th>actions</th>
  </tr>

  <%= render @games %>
</table>

slayfield/app/views/games/show.html.erb
<h1> Game #<%= @game.id %> (turn <%= @game.turn %>)</h1>

<% @winner = @game.winner  %>
<% if @winner %>
  <h1><%= @winner.name %> WON! </h1>
<% end %>

<%= render @teams %>

<div id='log'>
  <% @game.logs.order(turn: :desc, step: :desc).each do |log| %>
    <p><%= log.action %> </p>
  <% end %>
</div>

<p>
  <%= link_to 'Back', games_path %>
</p>

slayfield/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slayfield</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>